#!/usr/bin/env bash
# jstack-setup — install the jstack skills into an agent harness and write config.
#
# Usage:
#   setup.sh [--skills-dir DIR] [--link] [--non-interactive] [--print-only]
#
#   --skills-dir DIR   Install target (default: auto-detect, fallback ~/.claude/skills)
#   --link             Symlink skills instead of copying (edits track the repo)
#   --non-interactive  Never prompt; write config from defaults (also auto when no TTY)
#   --print-only       Detect + report what it would do, make no changes
#
# Idempotent: re-running re-syncs skills and leaves an existing config.env untouched.
set -euo pipefail

# --- locate repo ------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"   # scripts -> jstack-setup -> skills -> repo
SKILLS_SRC="$REPO_ROOT/skills"
ENV_EXAMPLE="$REPO_ROOT/.env.example"
CONFIG_DIR="$HOME/.jstack"
CONFIG_FILE="$CONFIG_DIR/config.env"

# --- args -------------------------------------------------------------------
SKILLS_DIR=""
MODE_LINK=0
NON_INTERACTIVE=0
PRINT_ONLY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --skills-dir) SKILLS_DIR="$2"; shift 2 ;;
    --link) MODE_LINK=1; shift ;;
    --non-interactive) NON_INTERACTIVE=1; shift ;;
    --print-only) PRINT_ONLY=1; shift ;;
    -h|--help) sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 64 ;;
  esac
done
# No TTY (e.g. run by an agent) => never block on prompts.
[ -t 0 ] || NON_INTERACTIVE=1

say() { printf '%s\n' "$*"; }
hr()  { printf -- '----------------------------------------\n'; }

# --- 1. choose install target ----------------------------------------------
if [ -z "$SKILLS_DIR" ]; then
  CANDIDATES=("$HOME/.claude/skills" "$HOME/.agents/skills" "$HOME/.hermes/skills")
  FOUND=()
  for d in "${CANDIDATES[@]}"; do [ -d "$d" ] && FOUND+=("$d"); done
  if [ "${#FOUND[@]}" -eq 1 ]; then
    SKILLS_DIR="${FOUND[0]}"
  elif [ "${#FOUND[@]}" -gt 1 ] && [ "$NON_INTERACTIVE" -eq 0 ]; then
    say "Multiple harness skill dirs found:"
    i=1; for d in "${FOUND[@]}"; do say "  $i) $d"; i=$((i+1)); done
    printf "Install into which? [1] "; read -r choice || choice=1
    SKILLS_DIR="${FOUND[$(( ${choice:-1} - 1 ))]}"
  else
    SKILLS_DIR="${FOUND[0]:-$HOME/.claude/skills}"
  fi
fi

say "jstack setup"
hr
say "repo:        $REPO_ROOT"
say "install to:  $SKILLS_DIR  ($([ "$MODE_LINK" -eq 1 ] && echo symlink || echo copy))"
say "config:      $CONFIG_FILE"
[ "$NON_INTERACTIVE" -eq 1 ] && say "mode:        non-interactive"
hr

if [ "$PRINT_ONLY" -eq 1 ]; then
  say "Would install skills:"; for s in "$SKILLS_SRC"/*/; do say "  - $(basename "$s")"; done
  exit 0
fi

# --- 2. install skills ------------------------------------------------------
mkdir -p "$SKILLS_DIR"
installed=0
for s in "$SKILLS_SRC"/*/; do
  name="$(basename "$s")"
  dest="$SKILLS_DIR/$name"
  if [ "$MODE_LINK" -eq 1 ]; then
    rm -rf "$dest"
    ln -s "${s%/}" "$dest"
  else
    rm -rf "$dest"
    cp -R "${s%/}" "$dest"
  fi
  installed=$((installed+1))
done
say "Installed $installed skill(s) into $SKILLS_DIR"

# --- 3. write config --------------------------------------------------------
mkdir -p "$CONFIG_DIR"
if [ -f "$CONFIG_FILE" ]; then
  say "Config already exists, leaving it untouched: $CONFIG_FILE"
elif [ "$NON_INTERACTIVE" -eq 1 ]; then
  if [ -f "$ENV_EXAMPLE" ]; then cp "$ENV_EXAMPLE" "$CONFIG_FILE"; else : > "$CONFIG_FILE"; fi
  say "Wrote default config: $CONFIG_FILE  (edit it to set GOOGLE_CLOUD_PROJECT, persona, etc.)"
else
  say "Configure jstack (press enter to accept the default):"
  read -r -p "  Your name / persona [the user]: " v_persona || true
  read -r -p "  Second-brain vault path [~/second-brain]: " v_brain || true
  read -r -p "  GCP project for jstack-vision (optional): " v_gcp || true
  {
    echo "# jstack config — generated by jstack-setup"
    echo "JSTACK_PERSONA_NAME=${v_persona:-the user}"
    echo "SECOND_BRAIN_PATH=${v_brain:-$HOME/second-brain}"
    echo "GOOGLE_CLOUD_PROJECT=${v_gcp:-}"
    echo "GOOGLE_CLOUD_LOCATION=us-central1"
    echo "GEMINI_VISION_MODEL=gemini-2.5-flash"
    echo "CLAUDE_PROJECTS_DIR=$HOME/.claude/projects"
    echo "JSTACK_HANDOFF_DIR=$HOME/.jstack/handoffs"
    echo "ADSCAN_DIR=$HOME/builds/adscan"
  } > "$CONFIG_FILE"
  say "Wrote config: $CONFIG_FILE"
fi
mkdir -p "$HOME/.jstack/handoffs" "$HOME/.jstack/transcripts"

# --- 4. capability probes (non-fatal) --------------------------------------
hr; say "Capability check:"
probe() { # name, condition-cmd, ok-msg, miss-msg
  if eval "$2" >/dev/null 2>&1; then say "  [ok]   $1 — $3"; else say "  [miss] $1 — $4"; fi
}
probe "python3" "command -v python3" "available" "install Python 3 for the transcript/search skills"
probe "codex"   "command -v codex"   "installed (enables background-codex advisor)" "optional: npm i -g @openai/codex for /jstack-challenge codex mode"
if command -v codex >/dev/null 2>&1; then
  if [ -n "${CODEX_API_KEY:-}${OPENAI_API_KEY:-}" ] || [ -f "$HOME/.codex/auth.json" ]; then
    say "  [ok]   codex auth — found (key env or ~/.codex/auth.json)"
  else
    say "  [miss] codex auth — run 'codex login' to enable the codex advisor"
  fi
fi
probe "gemini"  "command -v gemini"  "installed (jstack-vision ready once GOOGLE_CLOUD_PROJECT is set)" "optional: brew install gemini-cli for jstack-vision"
probe "ffmpeg"  "command -v ffmpeg"  "available (jstack-adscan video posters)" "optional: needed only for jstack-adscan video frames"

# --- 5. next steps ----------------------------------------------------------
hr; say "Next steps:"
say "  1. Restart your agent / reload skills so it sees jstack-*."
say "  2. Edit $CONFIG_FILE to set GOOGLE_CLOUD_PROJECT (vision) and your persona."
say "  3. jstack-vision: add the wrapper to PATH:"
say "       export PATH=\"$REPO_ROOT/vendor/gemini-vision:\$PATH\""
say "  4. jstack-brainwork / jstack-savetobrain need a second-brain (llm-wiki) vault at SECOND_BRAIN_PATH."
say "  5. jstack-adscan needs a separate adscan repo at ADSCAN_DIR."
say "Done."
