#!/usr/bin/env python3
"""docs_index.py — deterministic file registry + linter for a venture's docs/.

Mirrors the second-brain's `sb.py index`/`check` for a venture repo's `docs/` tree:
regenerates `docs/index.md` (a router that says what every durable planning/research
doc is about, grouped by zone) and lints naming + frontmatter so a cold agent can
navigate the docs without opening every file. The index is GENERATED — never
hand-edited — so it can never drift from the tree.

Canonical durable zone (indexed):
  docs/strategy/*.md            strategy and architecture name: YYYY-MM-DD-kebab-topic.md

Legacy zones (indexed, never new destinations):
  docs/build/*.md               prior code/build artifacts
  docs/superpowers/**           prior planning material
  docs/decisions.md             operational log          (linked, not itemized)

Unindexed zones:
  docs/scratch/**               legacy working drops; preserve, do not add new files
  ../.scratch/**                configured local tracker's specs/tickets (outside docs/)

Per-doc frontmatter (lightweight, agent-native — the index reads THIS, never the body):
  title:   human title
  summary: one line — what the doc is about + its verdict/state
  status:  active | accepted | proposed | draft | superseded | deprecated | archived
  (optional) type, created, updated, supersedes, superseded_by

Subcommands:
  index [--write]     regenerate docs/index.md from frontmatter (stdout unless --write)
  lint                validate naming + frontmatter + supersession + index freshness (exit 1 on error)
  backfill [--write]  add missing frontmatter (title<-H1, summary<-first prose line,
                      status<-parsed or 'active'); safe + idempotent
  brain-link [--write] create the brain-visible symlink to this canonical index
  brain-link-lint     validate that the brain-visible artifact is a working symlink, never a copy

Target the repo with --venture <slug> (under --ventures-base) or --repo <path>.
Use --slug <slug> to override the repo directory name when a repository has a
human-readable path but needs a stable satellite/brain identity.
Pass `--satellite-kind build` for a BUILD repo so its brain-visible index lives under
`wiki/personal/builds/`; the default remains `venture` for compatibility.
Determinism: sorted, stable output; no LLM. Same input tree -> same index bytes.

Usage:
  docs_index.py index  --write --venture second-brain-agency
  docs_index.py lint          --venture second-brain-agency
  docs_index.py backfill --write --repo /tmp/v/second-brain-agency   # testing override
  docs_index.py index --write --repo "~/builds/Fopus StudyWorld" --slug fopus-studyworld
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from datetime import date
from pathlib import Path

# ---------------------------------------------------------------------------
# constants
# ---------------------------------------------------------------------------

ADR_RE = re.compile(r"^(\d{4})-[a-z0-9][a-z0-9-]*\.md$")
SPEC_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-[a-z0-9][a-z0-9-]*\.md$")

# live == the decision/doc is in force. superseded/deprecated/archived == historical.
VALID_STATUS = {"active", "accepted", "proposed", "draft",
                "superseded", "deprecated", "archived"}
LIVE_STATUS = {"active", "accepted", "proposed", "draft"}
REQUIRED_KEYS = ("title", "summary", "status")

GEN_MARK = "<!-- GENERATED by docs_index.py — do not hand-edit -->"

META_KEY_RE = re.compile(
    r"^\**\s*(status|date|deciders?|relates?-to|lineage|evidence(\s+base)?|"
    r"artifact|purpose|source(\s+clips)?|updated|created|author|tags|scope)\b", re.I)


# ---------------------------------------------------------------------------
# tiny helpers
# ---------------------------------------------------------------------------

def die(msg: str, code: int = 1) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(code)


def split_frontmatter(text: str):
    """Return (fm_text, body). fm_text is '' when there is no leading --- block."""
    if text.startswith("---\n") or text.startswith("---\r\n"):
        end = text.find("\n---", 3)
        if end != -1:
            fm = text[text.find("\n") + 1:end]
            rest = text[end + len("\n---"):]
            rest = rest.lstrip("\r")
            if rest.startswith("\n"):
                rest = rest[1:]
            return fm, rest
    return "", text


def fm_get(fm: str, key: str):
    for line in fm.splitlines():
        m = re.match(rf"^{re.escape(key)}\s*:\s*(.*)$", line)
        if m:
            v = m.group(1).strip()
            if len(v) >= 2 and v[0] in "\"'" and v[-1] == v[0]:
                v = v[1:-1].replace('\\"', '"').replace("\\\\", "\\")
            return v
    return None


def first_h1(body: str) -> str:
    for raw in body.splitlines():
        line = raw.strip()
        if line.startswith("# "):
            return line[2:].strip()
    for raw in body.splitlines():          # fallback: any heading
        line = raw.strip()
        if line.startswith("#"):
            return line.lstrip("#").strip()
    return ""


def _collect_para(lines: list[str]) -> str:
    """Collect the first sentence-like paragraph from a run of raw lines.
    A start line must be at column 0 (indented lines are wrapped continuations of
    metadata/bullets), non-heading, non-metadata, non-list, and sentence-like."""
    started = False
    para: list[str] = []
    for raw in lines:
        line = raw.strip()
        if not started:
            if not line or line == "---":
                continue
            if raw[:1].isspace():                       # indented => a wrapped continuation
                continue
            if line.startswith(("#", "!", ">", "|", "```", "<", "- ", "* ", "1.")):
                continue
            if META_KEY_RE.match(line):
                continue
            if "·" in line and re.search(r"status\s*:", line, re.I):
                continue
            if not re.match(r"^[A-Z\"']", line):        # must look like a sentence start
                continue
            started = True
            para.append(line)
        else:
            if not line or line.startswith(("#", "|", "```", ">", "- ", "* ")):
                break
            para.append(line)
    text = " ".join(para)
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", text)   # links/images -> text
    text = re.sub(r"[*_`]+", "", text)                        # emphasis
    text = " ".join(text.split())
    if not text:
        return ""
    m = re.search(r"(.+?[.!?])(?:\s|$)", text)
    if m and len(m.group(1)) >= 40:
        return m.group(1).strip()
    return text


def first_prose_paragraph(body: str) -> str:
    """Prefer prose after the first '## ' section heading (skips the title +
    metadata preamble reliably); fall back to the first prose anywhere in the body."""
    lines = body.splitlines()
    start = 0
    for i, raw in enumerate(lines):
        if raw.strip().startswith("## "):
            start = i + 1
            break
    for region in (lines[start:], lines):
        para = _collect_para(region)
        if para:
            return para
    return ""


LABEL_RE = re.compile(r"^\s*-?\s*\*{0,2}(context|purpose|summary|problem)\*{0,2}\s*:\s*(.*)$", re.I)


def _first_sentence(text: str) -> str:
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"[*_`]+", "", text)
    text = " ".join(text.split())
    if not text:
        return ""
    m = re.search(r"(.+?[.!?])(?:\s|$)", text)
    return m.group(1).strip() if (m and len(m.group(1)) >= 40) else text


def labeled_summary(body: str) -> str:
    """Use an explicit Context:/Purpose:/Summary:/Problem: field (+ its indented
    wrapped continuation) when present — the cleanest one-line gist for bullet-metadata docs."""
    lines = body.splitlines()
    for i, raw in enumerate(lines):
        m = LABEL_RE.match(raw)
        if m:
            parts = [m.group(2).strip()]
            for cont in lines[i + 1:]:
                if not cont.strip() or not cont[:1].isspace():   # stop at blank or a col-0 line
                    break
                parts.append(cont.strip())
            return _first_sentence(" ".join(parts))
    return ""


def derive_summary(body: str) -> str:
    return labeled_summary(body) or first_prose_paragraph(body)


def truncate(s: str, n: int = 200) -> str:
    s = " ".join((s or "").split())
    if len(s) <= n:
        return s
    return s[:n].rsplit(" ", 1)[0].rstrip(",.;:") + "…"


def yaml_quote(s: str) -> str:
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse_existing_status(body: str):
    head = "\n".join(body.splitlines()[:20])
    m = re.search(r"status\s*[:=]\s*([A-Za-z]+)", head, re.I)
    return m.group(1).lower() if m else None


def parse_existing_date(body: str):
    head = "\n".join(body.splitlines()[:20])
    m = re.search(r"date\s*[:=]?\s*\**\s*(\d{4}-\d{2}-\d{2})", head, re.I)
    if m:
        return m.group(1)
    m = re.search(r"(\d{4}-\d{2}-\d{2})", head)
    return m.group(1) if m else None


def infer_type(name: str, zone: str) -> str:
    if zone == "legacy-adr":
        return "adr"
    if zone == "strategy":
        return "strategy"
    if zone == "legacy-build":
        return "build"
    low = name.lower()
    for kw in ("premortem", "research", "design"):
        if kw in low:
            return kw
    return "spec"


# ---------------------------------------------------------------------------
# doc model
# ---------------------------------------------------------------------------

def load_doc(path: Path, zone: str) -> dict:
    text = path.read_text()
    fm, body = split_frontmatter(text)
    title = fm_get(fm, "title") or first_h1(body) or path.stem
    summary = fm_get(fm, "summary") or truncate(derive_summary(body)) or "(no summary)"
    status = (fm_get(fm, "status") or parse_existing_status(body) or "").lower()
    return {
        "path": path, "zone": zone, "name": path.name,
        "title": title, "summary": summary, "status": status,
        "type": fm_get(fm, "type") or infer_type(path.name, zone),
        "supersedes": fm_get(fm, "supersedes"),
        "superseded_by": fm_get(fm, "superseded_by"),
        "has_fm": bool(fm.strip()),
        "fm": fm, "body": body,
    }


def collect(docs_dir: Path):
    adr_dir = docs_dir / "superpowers" / "adr"
    spec_dir = docs_dir / "superpowers" / "specs"
    strategy_dir = docs_dir / "strategy"
    build_dir = docs_dir / "build"
    legacy_adrs = [load_doc(p, "legacy-adr") for p in sorted(adr_dir.glob("*.md"))]
    legacy_specs = [load_doc(p, "legacy-spec") for p in sorted(spec_dir.glob("*.md"))]
    strategy = [load_doc(p, "strategy") for p in sorted(strategy_dir.glob("*.md"))]
    legacy_build = [load_doc(p, "legacy-build") for p in sorted(build_dir.glob("*.md"))]
    return strategy, legacy_build, legacy_adrs, legacy_specs


def legacy_scratch_count(docs_dir: Path) -> int:
    d = docs_dir / "scratch"
    if not d.is_dir():
        return 0
    return sum(1 for p in d.rglob("*") if p.is_file() and p.name != ".gitkeep")


# ---------------------------------------------------------------------------
# index rendering
# ---------------------------------------------------------------------------

def status_cell(d: dict) -> str:
    st = d["status"] or "?"
    if st in ("superseded", "deprecated") and d.get("superseded_by"):
        return f"{st} → {d['superseded_by']}"
    return st


def render_index(docs_dir: Path, slug: str, strategy, legacy_build, legacy_adrs, legacy_specs,
                 satellite_kind: str = "venture") -> str:
    def rel(p: Path) -> str:
        return p.relative_to(docs_dir).as_posix()

    L: list[str] = []
    target = f"--venture {slug}" if satellite_kind == "venture" else "--repo . --satellite-kind build"
    L.append("# docs/ — file registry (generated)")
    L.append("")
    L.append(f"> {GEN_MARK}")
    L.append("> Regenerate after ANY add/edit under `docs/`:")
    L.append(f">     python3 ~/jstack/skills/jstack-init/scripts/docs_index.py index --write {target}")
    L.append("> Lint: `docs_index.py lint`. Naming + frontmatter convention: `docs/CLAUDE.md`.")
    L.append("> Canonical workspace artifacts live here; the brain exposes this index by symlink only.")
    L.append(f"> Brain-visible no-drift reference: `~/second-brain/wiki/personal/{satellite_kind}s/{slug}.docs-index` (symlink to this file).")
    L.append("")

    def render_dated_section(heading: str, docs: list[dict], what: str) -> None:
        L.append(heading)
        L.append("")
        if docs:
            L.append(f"| Date | Doc | Status | {what} |")
            L.append("|------|-----|--------|------------|")
            for d in sorted(docs, key=lambda x: x["name"], reverse=True):
                m = SPEC_RE.match(d["name"])
                dt = m.group(1) if m else "—"
                L.append(f"| {dt} | [{d['title']}]({rel(d['path'])}) | {status_cell(d)} | {d['summary']} |")
        else:
            L.append("_(none yet)_")
        L.append("")

    render_dated_section(
        "## Strategy — `strategy/`  ·  name: `YYYY-MM-DD-kebab-topic.md`",
        strategy, "What it decides")
    L.append("## Legacy build material — `build/` (preserved)")
    L.append("")
    L.append("Historical technical decisions and design records. Do not add new files here; new durable rationale belongs in `strategy/`.")
    L.append("")
    render_dated_section(
        "### Historical build records",
        legacy_build, "What it is")

    L.append("## Legacy planning material — `superpowers/` (preserved)")
    L.append("")
    if legacy_adrs:
        L.append("### Legacy decisions — `superpowers/adr/`  ·  name: `NNNN-kebab-topic.md`")
        L.append("")
        L.append("| # | Doc | Status | What it decides |")
        L.append("|---|-----|--------|-----------------|")
        for d in sorted(legacy_adrs, key=lambda x: x["name"]):
            num = d["name"][:4]
            L.append(f"| {num} | [{d['title']}]({rel(d['path'])}) | {status_cell(d)} | {d['summary']} |")
    else:
        L.append("_(none yet)_")
    L.append("")
    L.append("### Legacy specs, designs & research — `superpowers/specs/`  ·  name: `YYYY-MM-DD-kebab-topic.md`")
    L.append("")
    if legacy_specs:
        L.append("| Date | Doc | Status | What it is |")
        L.append("|------|-----|--------|------------|")
        for d in sorted(legacy_specs, key=lambda x: x["name"], reverse=True):
            m = SPEC_RE.match(d["name"])
            dt = m.group(1) if m else "—"
            L.append(f"| {dt} | [{d['title']}]({rel(d['path'])}) | {status_cell(d)} | {d['summary']} |")
    else:
        L.append("_(none yet)_")
    L.append("")

    L.append("## Operational log")
    L.append("")
    L.append("- [decisions.md](decisions.md) — append-only operational decision log "
             "(repo/process/tooling choices only).")
    L.append("")
    L.append("## Unindexed working areas")
    L.append("")
    n = legacy_scratch_count(docs_dir)
    L.append(f"- `scratch/` — {n} legacy working file(s), preserved and not indexed. Do not add new files here.")
    L.append("- `../.scratch/` — local tracker specs/tickets when that tracker is configured; outside this registry.")
    L.append("")
    return "\n".join(L)


# ---------------------------------------------------------------------------
# subcommands
# ---------------------------------------------------------------------------

def cmd_index(docs_dir: Path, slug: str, write: bool, satellite_kind: str = "venture") -> int:
    strategy, legacy_build, legacy_adrs, legacy_specs = collect(docs_dir)
    out = render_index(docs_dir, slug, strategy, legacy_build, legacy_adrs, legacy_specs, satellite_kind)
    target = docs_dir / "index.md"
    if write:
        target.write_text(out)
        legacy_count = len(legacy_build) + len(legacy_adrs) + len(legacy_specs)
        print(f"wrote {target}  ({len(strategy)} strategy, {legacy_count} legacy)")
    else:
        sys.stdout.write(out)
    return 0


def cmd_lint(docs_dir: Path, slug: str, satellite_kind: str = "venture") -> int:
    strategy, legacy_build, legacy_adrs, legacy_specs = collect(docs_dir)
    docs = strategy + legacy_build + legacy_adrs + legacy_specs
    errors: list[str] = []
    warnings: list[str] = []
    adr_nums = {d["name"][:4] for d in legacy_adrs}

    for d in docs:
        rel = d["path"].relative_to(docs_dir).as_posix()
        # naming
        if d["zone"] == "strategy" and not SPEC_RE.match(d["name"]):
            errors.append(f"{rel}: filename must match YYYY-MM-DD-kebab-topic.md")
        elif d["zone"] == "legacy-adr" and not ADR_RE.match(d["name"]):
            warnings.append(f"{rel}: legacy ADR filename does not match NNNN-kebab-topic.md")
        elif d["zone"] in ("legacy-spec", "legacy-build") and not SPEC_RE.match(d["name"]):
            warnings.append(f"{rel}: legacy filename does not match YYYY-MM-DD-kebab-topic.md")
        # frontmatter presence
        if not d["has_fm"]:
            message = f"{rel}: missing YAML frontmatter (run: docs_index.py backfill --write)"
            (errors if d["zone"] == "strategy" else warnings).append(message)
            continue
        for k in REQUIRED_KEYS:
            if not fm_get(d["fm"], k):
                message = f"{rel}: frontmatter missing required key '{k}'"
                (errors if d["zone"] == "strategy" else warnings).append(message)
        # status vocab
        if d["status"] and d["status"] not in VALID_STATUS:
            message = f"{rel}: status '{d['status']}' not in {sorted(VALID_STATUS)}"
            (errors if d["zone"] == "strategy" else warnings).append(message)
        # supersession integrity
        if d["status"] in ("superseded", "deprecated") and not d["superseded_by"]:
            message = f"{rel}: status={d['status']} requires a superseded_by: pointer"
            (errors if d["zone"] == "strategy" else warnings).append(message)
        if d["zone"] == "legacy-adr" and d["superseded_by"]:
            ref = re.sub(r"\D", "", d["superseded_by"])[:4].zfill(4)
            if ref not in adr_nums:
                warnings.append(f"{rel}: superseded_by '{d['superseded_by']}' matches no ADR number")
        if d["summary"] == "(no summary)":
            warnings.append(f"{rel}: empty summary")

    # index freshness
    target = docs_dir / "index.md"
    expected = render_index(docs_dir, slug, strategy, legacy_build, legacy_adrs, legacy_specs, satellite_kind)
    if not target.exists():
        errors.append("index.md missing (run: docs_index.py index --write)")
    elif target.read_text() != expected:
        errors.append("index.md is stale (run: docs_index.py index --write)")

    for w in warnings:
        print(f"WARN {w}")
    for e in errors:
        print(f"ERR  {e}")
    print(f"\n{len(docs)} doc(s) checked · {len(errors)} error(s) · {len(warnings)} warning(s)")
    return 1 if errors else 0


CORE_KEYS = ("title", "summary", "status", "type", "created", "updated")


def cmd_backfill(docs_dir: Path, write: bool, refresh: bool) -> int:
    strategy, legacy_build, legacy_adrs, legacy_specs = collect(docs_dir)
    today = date.today().isoformat()
    changed = 0
    for d in strategy + legacy_build + legacy_adrs + legacy_specs:
        path = d["path"]
        rel = path.relative_to(docs_dir).as_posix()
        fm, body = d["fm"], d["body"]

        # values derived fresh from the body prose (source of truth)
        raw_status = (fm_get(fm, "status") or parse_existing_status(body) or "active").lower()
        m = SPEC_RE.match(path.name)
        derived = {
            "title": first_h1(body) or path.stem,
            "summary": truncate(derive_summary(body)) or "(no summary)",
            # normalize any out-of-vocab parsed status (e.g. 'durable', 'finalized')
            "status": raw_status if raw_status in VALID_STATUS else "active",
            "type": infer_type(path.name, d["zone"]),
            "created": (m.group(1) if m else None) or parse_existing_date(body) or today,
            "updated": today,
        }

        missing = [k for k in CORE_KEYS if fm_get(fm, k) is None]
        if d["has_fm"] and not missing and not refresh:
            continue  # already complete and not forcing a refresh

        # on refresh, recompute title/summary/status/type/updated from the body;
        # otherwise keep whatever the frontmatter already has and only fill gaps.
        # `created` is never overwritten once set.
        force = {"title", "summary", "status", "type", "updated"} if refresh else set()
        final = {}
        for k in CORE_KEYS:
            cur = fm_get(fm, k)
            final[k] = derived[k] if (k in force or cur is None) else cur
        final["created"] = fm_get(fm, "created") or derived["created"]

        # preserve any non-core frontmatter keys verbatim (e.g. supersedes, deciders)
        extras = [ln for ln in fm.splitlines()
                  if (km := re.match(r"^([A-Za-z0-9_-]+)\s*:", ln)) and km.group(1) not in CORE_KEYS]

        new_lines = []
        for k in CORE_KEYS:
            v = yaml_quote(final[k]) if k in ("title", "summary") else final[k]
            new_lines.append(f"{k}: {v}")
        new_lines.extend(extras)

        new_fm = "\n".join(new_lines)
        new_text = f"---\n{new_fm}\n---\n{body}" if not body.startswith("\n") else f"---\n{new_fm}\n---{body}"
        changed += 1
        if write:
            path.write_text(new_text)
            print(f"{'refreshed' if refresh else 'backfilled'} {rel}")
        else:
            print(f"would {'refresh' if refresh else 'backfill'} {rel}  (status={final['status']})")
    verb = "refreshed" if refresh else "backfilled"
    print(f"\n{changed} file(s) {verb if write else 'need ' + ('refresh' if refresh else 'backfill')}")
    return 0


# ---------------------------------------------------------------------------
# brain-visible index link
# ---------------------------------------------------------------------------

def brain_link_path(brain: Path, slug: str, satellite_kind: str = "venture") -> Path:
    """Stable, non-.md link path so sb.py never treats the generated catalog as a wiki page."""
    return brain / "wiki" / "personal" / f"{satellite_kind}s" / f"{slug}.docs-index"


def resolve_brain(args) -> Path:
    brain = Path(args.brain).expanduser().resolve()
    if not brain.is_dir():
        die(f"brain not found: {brain}")
    if not (brain / "wiki").is_dir():
        die(f"no wiki/ in brain: {brain}")
    return brain


def cmd_brain_link(docs_dir: Path, slug: str, brain: Path, write: bool,
                   satellite_kind: str = "venture") -> int:
    source = docs_dir / "index.md"
    if not source.is_file():
        print("ERR  docs/index.md missing (run: docs_index.py index --write)")
        return 1
    link = brain_link_path(brain, slug, satellite_kind)
    target = Path(os.path.relpath(source.resolve(), start=link.parent))

    if link.is_symlink():
        if link.resolve() == source.resolve():
            print(f"brain docs index link: ok {link} -> {target}")
            return 0
        print(f"ERR  brain docs index link points elsewhere: {link} -> {link.readlink()}")
        return 1
    if link.exists():
        print(f"ERR  brain docs index artifact must be a symlink, not a copied file: {link}")
        return 1
    if not write:
        print(f"would create brain docs index link: {link} -> {target}")
        return 0

    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(target)
    print(f"created brain docs index link: {link} -> {target}")
    return 0


def cmd_brain_link_lint(docs_dir: Path, slug: str, brain: Path,
                        satellite_kind: str = "venture") -> int:
    source = docs_dir / "index.md"
    link = brain_link_path(brain, slug, satellite_kind)
    errors: list[str] = []
    if not source.is_file():
        errors.append("docs/index.md missing (run: docs_index.py index --write)")
    if not link.is_symlink():
        errors.append(f"brain docs index artifact must be a symlink: {link}")
    elif not link.exists():
        errors.append(f"brain docs index symlink is broken: {link} -> {link.readlink()}")
    elif source.is_file() and link.resolve() != source.resolve():
        errors.append(f"brain docs index symlink points elsewhere: {link} -> {link.readlink()}")

    for error in errors:
        print(f"ERR  {error}")
    if errors:
        return 1
    print(f"brain docs index link: GREEN ({link} -> {link.readlink()})")
    return 0


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def resolve_docs(args) -> tuple[Path, str]:
    if args.repo:
        repo = Path(args.repo).expanduser()
    elif args.venture:
        repo = Path(args.ventures_base).expanduser() / args.venture
    else:
        die("target the repo with --venture <slug> or --repo <path>")
    repo = repo.resolve()  # so repo.name is the real dir (slug) even for --repo .
    if not repo.is_dir():
        die(f"repo not found: {repo}")
    docs = repo / "docs"
    if not docs.is_dir():
        die(f"no docs/ in {repo}")
    # A repo may intentionally have a human-readable directory name.  Keep the
    # stable satellite identity independent from that path when explicitly set.
    return docs, args.slug or repo.name


def main() -> int:
    ap = argparse.ArgumentParser(description="Deterministic docs/ registry + linter for a venture repo.")
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("index", "lint", "backfill", "brain-link", "brain-link-lint"):
        sp = sub.add_parser(name)
        sp.add_argument("--venture", help="venture slug (dir under --ventures-base)")
        sp.add_argument("--repo", help="explicit repo root (overrides --venture)")
        sp.add_argument("--slug", help="stable satellite identity (overrides repo directory name)")
        sp.add_argument("--ventures-base", default=str(Path.home() / "ventures"),
                        help="override ventures root (testing)")
        sp.add_argument("--satellite-kind", choices=("venture", "build"), default="venture",
                        help="brain registry kind (default: venture; use build for ~/builds repos)")
        if name in ("index", "backfill", "brain-link"):
            sp.add_argument("--write", action="store_true", help="write changes (else dry-run to stdout)")
        if name == "backfill":
            sp.add_argument("--refresh", action="store_true",
                            help="recompute title/summary/status from the body even if frontmatter exists")
        if name in ("brain-link", "brain-link-lint"):
            sp.add_argument("--brain", default=str(Path.home() / "second-brain"),
                            help="second-brain root (testing override)")
    args = ap.parse_args()

    docs, slug = resolve_docs(args)
    if args.cmd == "index":
        return cmd_index(docs, slug, args.write, args.satellite_kind)
    if args.cmd == "lint":
        return cmd_lint(docs, slug, args.satellite_kind)
    if args.cmd == "backfill":
        return cmd_backfill(docs, args.write, args.refresh)
    if args.cmd == "brain-link":
        return cmd_brain_link(docs, slug, resolve_brain(args), args.write, args.satellite_kind)
    if args.cmd == "brain-link-lint":
        return cmd_brain_link_lint(docs, slug, resolve_brain(args), args.satellite_kind)
    return 2


if __name__ == "__main__":
    sys.exit(main())
